inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.2
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'
