language: ruby
cache: bundler
sudo: false
dist: trusty

rvm:
  - 2.5.0
  - 2.6.4

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake best_type:ci
